"""empty message

Revision ID: d2c06dcbe03c
Revises: 
Create Date: 2019-12-21 14:38:07.750632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c06dcbe03c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example',
    sa.Column('primary_key', sa.Integer(), nullable=False),
    sa.Column('int_row', sa.String(), nullable=True),
    sa.Column('str_row', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('primary_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('example')
    # ### end Alembic commands ###
